scalacenter/tasty-query

- .scalafmt.conf
- README.md
- build.sbt
- js/src/main/scala/Main.scala
- jvm/src/main/scala/Main.scala
- jvm/src/test/scala/ReadTreeSuite.scala
- project/plugins.sbt
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Signature.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TastyUnpickler.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/EmptyClass.scala
- test-sources/src/main/scala/empty_class/EmptyClass.scala
The unpickler reads the name table and unpickles the AST section. This PR adds the unpickler and minimalistic structures to store the result (Names, Trees, Types).
> Create a simplistic unpickler which can unpickle a TASTy file, produced from an empty class

- build.sbt
- project/build.properties
- project/plugins.sbt
Update dependencies' versions accordingly. Remove the dotty plugin since it's not needed anymore.
> Update the project's scala version to 3.0.0

- jvm/src/main/scala/tastyquery/Main.scala
- shared/src/main/scala/tastyquery/api/TastyQuery.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
add a simple way to debug definitions in a class from the CLI
> debug definitions from Main

- jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
Later, we will also need to fill them in when reading from class files and Scala 2 pickles.
> Fill in the declaredType of methods and fields read from TASTy.

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/ast/Flags.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- Read modifiers
- Normalize flags according to tag and owner
> Add flags and privateWithin

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- test-sources/src/main/scala/javadefined/BagOfJavaDefinitions.java
I based this on `main`. If it's merged I'll rebase #77 on top of these.
> Fix THIStpe and remove raw type support

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/RefinedTypeTree.scala
At least, we don't crash when reading them. We can also read
recursive ThisType references to themselves.
> Support RefinedTypes a little bit more.

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/RefinedTypeTree.scala
That creates a new RecType which provides a binder unto itself.
> Read TASTy RECtype tag.

- jvm/src/test/scala/tastyquery/SignatureSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
> Don't crash when erasing array types

- jvm/src/test/scala/tastyquery/PositionSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/SignatureSuite.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- test-sources/src/main/scala/simple_trees/TypeMember.scala
> Handle erasure of type members and opaque type aliases.

- jvm/src/test/scala/tastyquery/LazyLoadingSuite.scala
- jvm/src/test/scala/tastyquery/PositionSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
In addition to removing existing boilerplate, this will reduce the diff when we transition to async test suites later, to support Scala.js.
> Test refactor: `testWithContext`-like helpers in restricted test suites.

- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Signature.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeMaps.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- shared/src/test/scala/tastyquery/SymbolSuite.scala
- shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/inheritance/CrossTasty.scala
- test-sources/src/main/scala/inheritance/SameTasty.scala
This does just enough to look up a symbol in a parent class
- parent types are now a list
- patch types of applied constructors
- patch signatures of constructor symbols
- add member lookup to class symbol
> Add inheritance

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
also standardise on paramRefss rather than paramSymss.
fixes #119
> add parents to scala 2 classes, erase scala 2 value classes

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeTrees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- test-sources/src/main/scala/javacompat/LazyVals.scala
> fix selection of pkg in tasty

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Following the instructions of https://github.com/sbt/sbt-ci-release
I have already set up the secrets on the repo.
> Set up sbt-ci-release.

- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
I believe this is the last of it. ;)
> Clean up the public API, part 4

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/MatchType.scala
fixes #17 
fixes #18 
fixes #134
> read match types in tasty unpickler

- build.sbt
- tasty-query/js/src/main/scala/tastyquery/nodejs/NodeFS.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/PositionUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/Paths.scala
In particular, `-deprecation` and `-Xfatal-warnings`.
> Stricter compiler options.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
Last small changes before a v0.2.0 release.
> Expose isSameType and test linearization

- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
attempting to resolve the actual symbol still fails
> can reference inner class in signatures

- tasty-query/shared/src/main/scala/tastyquery/Flags.scala
> Add a method FlagSet.show.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
For a better semantic categorization of what we can find in a `Block` and in a `PackageDef`.
> Introduce TopLevelTree and StatementTree.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/javadefined/BagOfJavaDefinitions.java
- test-sources/src/main/scala/javadefined/PkgPrivate.java
Set privateWithin for package private definitions. Set flags for classes.
> Correct owner for static java members.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
* Make it extend `Tree`, now that `TypeTree`s are `Tree`s too.
* Define its `symbol` member as an abstract member, rather than a constructor parameter; this reduces more boilerplate than it adds.
* Make `PackageDef` not a `DefTree`, since packages they do not actually define packages, and `PackageSymbol.tree` is always `None`.
> Clean up `DefTree`.

- build.sbt
Set `versionPolicyIntention` back to `BinaryCompatible` for the upcoming v0.5.1.
> Post release v0.5.0.

- build.sbt
Set `versionPolicyIntention` back to `BinaryCompatible` for the upcoming v0.6.1.
> Post release v0.6.0.

- build.sbt
Set `versionPolicyIntention` back to `BinaryCompatible` for the upcoming v0.7.1.
> Post release v0.7.0.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/TermRefIn.scala
I found those in the parboiled codebase, but I am not sure how to create a reproduction for them.
> Read TERMREFin nodes.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/javadefined/JavaAnnotWithDefault.java
- test-sources/src/main/scala/simple_trees/Annotations.scala
- test-sources/src/main/scala/simple_trees/AnonClassesInCtor.scala
- test-sources/src/main/scala/simple_trees/DoublePolyExtensions.scala
- test-sources/src/main/scala/simple_trees/Match.scala
Some of them I could reproduce without the external dependencies, but most of them I could not.
> Fix a bunch of issues found when reading the entire Scala 3 published ecosystem

- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
Discovered by the tasty checker.
> Small fixes.

- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Scala2Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/Tuples.scala
> More fixes for tasty-mima across Scala 2 and Scala 3

- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
> Add a basic pretty-printer for `TypeMappable`s.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
> Skip the problematic getClass() definitions in Scala 2 prim classes.

- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/UsingGiven.scala
> Read and expose whether `MethodType`s have the `implicit` or `using` modifier.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
> Two small cleanups in subtyping

- tasty-query/shared/src/main/scala/tastyquery/Traversers.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TestUtils.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
It allows to traverse trees with more control than `walkTrees`.
> Introduce Traversers.TreeTraverser.

- build.sbt
Set `versionPolicyIntention` back to `BinaryCompatible` for the upcoming v0.10.1.
> Post release v0.10.0.

- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/inheritance/Overrides.scala
> Fix #374: Fix matchesType between MethodType and Type.

- build.sbt
Set `versionPolicyIntention` to `BinaryAndSourceCompatible` for the upcoming v1.0.1.
> Post release v1.0.0.

- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
This was discovered by checking sbt-tasty-mima itself with TASTy-MiMa.
> Fix reading VALsym's without owner in the Scala 2 unpickler.
