scalacenter/tasty-query

- jvm/src/test/scala/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/Definitions.scala~2e44d26 (Link root package symbol's lifetime to context's lifetime)
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/nested/InQualifiedNestedPackage.scala
This PR introduces symbol organization.
1. Unpickling the AST section of a TASTy file now consists of two stages:
a. Symbol creation
b. Term creation.
Because all symbols are created before all terms, forward references are easy to handle.
2. Symbols are organized in a tree: each symbol knows its owner and is added to the declarations of the owner. The root of the tree is the <root> package.
> Organize symbols into a tree

- jvm/src/test/scala/BaseUnpicklingSuite.scala
- jvm/src/test/scala/ReadTreeSuite.scala
- jvm/src/test/scala/SymbolSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/NestedMethod.scala
This PR trims down the symbol tree: now it consists only of declarations, i.e. symbols that can be selected. All symbols are now also stored in the corresponding trees.
> Refine symbol declaration hierarchy and store symbols in the corresponding trees

- jvm/src/test/scala/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/TypeRefIn.scala
Ignore the namespace, similarly to other ...in tags.
> Read TYPEREFin in a stub way

- build.sbt
- jvm/src/main/scala/Main.scala
- jvm/src/test/scala/BaseUnpicklingSuite.scala
- jvm/src/test/scala/SymbolSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/api/ProjectReader.scala
- shared/src/main/scala/tastyquery/api/TastyQuery.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
This PR creates a scala 3 project reader, which takes a classpath and runs tree unpickler on all .tasty files on all classpath entries. To accommodate reading a project, two types of context are introduced: project-wide BaseContext and file-local FileContext.
> Implement a TASTy project reader

- jvm/src/test/scala/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
This PR introduces resolution of TermRef and TypeRef to their corresponding symbols.
In addition, this PR creates "standard" (`java.*` and `scala.*`) symbols in case they are not found. This is a temporary replacement for reading standard library.
> Resolve type and term references to symbols

- jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- jvm/src/test/scala/BaseUnpicklingSuite.scala
- jvm/src/test/scala/SymbolSuite.scala
we will not do anything in dotty compiler to special case symbolic package names, so error when user tries to find a symbolic package name.
> do not decode package names from classpath

- jvm/src/main/scala/Main.scala
- jvm/src/test/scala/tastyquery/BaseUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/api/ProjectReader.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- test-sources/src/main/scala/crosspackagetasty/BoxedConstants.scala
- test-sources/src/main/scala/mixjavascala/JavaBox.java
- test-sources/src/main/scala/mixjavascala/ScalaBox.scala
- assert that symbols can only be defined once.
- user must obtain top-level class symbol before
reading tasty - to obtain top-level class they
must first scan classpath.
- when scanning for a top-level class, create
symbols for all sibling classes in the same
package.
- only complete the members of a top-level class
on demand.
- same entry point to complete members both top-level
tasty and java/scala2 class files.
- adds example where a top-level class will be seen twice.
> create top level classes before reading tasty

- jvm/src/test/scala/tastyquery/BaseUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
`SymbolSuite` and `ReadTreeSuite` no longer allow dependencies between TASTy files unless explicitly specified. Dependencies should be tested in `TypeSuite`
> filter classpath to ensure no dependencies

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/ast/Constants.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
This requires synthetic declarations for `scala.Nothing` and `scala.Null`. They are added when we initialize the root context.
Applications do not receive types yet, because that will require `calculateType` to actually resolve symbols to get to functions' `MethodType`s.
> Give types to all the simple things.

- jvm/src/test/scala/tastyquery/BaseUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
The previous behavior of finding decls without loading anything was renamed as `getDeclInternal`. It is used in a couple of internal locations where we really have no business loading stuff, because we are already within code that loads.
Otherwise, methods that lookup symbols require an implicit `BaseContext` so that they can load things when necessary.
This allows to remove the hacks in the TypeSuite to load symbols. They get loaded automatically.
> Make default symbol/decl lookup load things when necessary.

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- test-sources/src/main/scala/simple_trees/OverloadedApply.scala
removes the "lazy" types `Application` and `TypeApplication`
> Tree types need context to compute

- jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- test-sources/src/main/scala/symbolic_--/lazyCons.scala
- test-sources/src/main/scala/symbolic_>>/lazyCons.scala
git crashes when trying to create a directory with '>' in it on Windows.
> Use Windows-friendly paths.

- jvm/src/test/scala/tastyquery/BaseUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
This will become necessary later, when we add a `BaseContext` parameter to `Symbol.tree`.
> Refactor ReadTreeSuite to give tests access to the BaseContext.

- jvm/src/test/scala/tastyquery/PositionSuite.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/SharedType.scala
This is a fix for the spans of `SHAREDterm` and `SHAREDtype`. In the previous implementation, the spans are incorrectly set to the span of the term/path they reference to.
> Fix the spans of shared tags

- jvm/src/test/scala/tastyquery/BaseUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/LazyLoadingSuite.scala
- jvm/src/test/scala/tastyquery/Paths.scala
- jvm/src/test/scala/tastyquery/PositionSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/RestrictedUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- jvm/src/test/scala/tastyquery/UnrestrictedUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/testutil/jdk/JavaTestPlatform.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/test/scala/tastyquery/testutil/TestPlatform.scala
> Make `Symbol.{declaredType,tree,declarations}` be auto-loading.

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
TypeBounds of the form `>: L <: H` used in AppliedTypes actually mean wildcards of the form `? >: L <: H`. Previously, we carried around `Type | TypeBounds` in many places. Now, we explicitly wrap `TypeBounds` in a `WildcardTypeBounds` in places where they mean wildcards.
A corresponding change is done to `TypeTree`s.
> Explicitly wrap TypeBounds as WildcardTypeBounds in AppliedTypes.

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
We did not actually call the provided `body` lambda, so the test was completely void.
> Fix ReadTreeSuite.testUnpickle; it was void.

- jvm/src/test/scala/tastyquery/LazyLoadingSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
store packages in decls by their short name.
remove the `lookup` method, migration is to cast to `DeclaringSymbol` and call `getDecl`
fixes #71
> Fix nested package lookup

- jvm/src/test/scala/tastyquery/LazyLoadingSuite.scala
- jvm/src/test/scala/tastyquery/Paths.scala
- jvm/src/test/scala/tastyquery/PositionSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/RestrictedUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
with these changes you can force top-level module class, module value, or class in any order. The root class will be selected
fixes #72
> unpickling top level classpath symbols can be done in any order

- .github/workflows/scala.yml
- jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- jvm/src/test/scala/tastyquery/testutil/jdk/JavaTestPlatform.scala
- shared/src/main/scala/tastyquery/Contexts.scala
This allows to actually inspect JDK classes like `java.lang.String`.
> Add the classes of the JDK to the test classpaths.

- jvm/src/test/scala/tastyquery/LazyLoadingSuite.scala
- jvm/src/test/scala/tastyquery/Paths.scala
- jvm/src/test/scala/tastyquery/PositionSuite.scala
- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- jvm/src/test/scala/tastyquery/RestrictedUnpicklingSuite.scala
- jvm/src/test/scala/tastyquery/SymbolSuite.scala
- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/api/ProjectReader.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
differences:
- getDecl will now force a
top level class' inner definitions,
this is not observable from the public API,
but some LazyLoadingSuite tests needed to
change.
- getTopLevelTasty now accepts any top level
class or module symbol.
add test case: assert no class for standalone object
experiment: replace `objclass"foo"` with `tname"foo" / obj`
> Only enter top level root symbols when reading the class/tasty file.

- jvm/src/test/scala/tastyquery/SignatureSuite.scala
- shared/src/main/scala/tastyquery/ast/Signature.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
`signedName` returns a `SignedName` with the `signature` if there is a signature, i.e., if the symbol has a `MethodicType`. Otherwise, it returns the regular `name`.
> Make Symbol.signature more robust and expose Symbol.signedName.

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
In Scala 2 pickles, they just have a simple TypeName, but in tasty-query they must have the module class suffix.
> Adjust the name of Scala 2 module classes.

- jvm/src/test/scala/tastyquery/ReadTreeSuite.scala
- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Signature.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/PositionUnpickler.scala
- shared/src/main/scala/tastyquery/reader/TastyUnpickler.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
There are two use cases for fully qualified names:
* in erased names for Signatures, and
* in pickled TASTy, for package definitions and references.
Package symbols used to have a fully qualified `name`, but that was inconsistent wrt. other symbols, whose `name`s are relative to their owner. Now, the `name` of package symbols is also a simple name relative to their parent packages.
> Separate FullyQualifiedName's out of the Name hierarchy.

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
In `scala.collection.:+` there is a type parameter `C <: SeqOps[A, CC, C]`.
This is what happen when we read the type of  `C`:
```
read type C
read symbol C
store symbol C
read declared type of symbol C
read type C
get symbol C from entries
store type C
set declared type of symbol C 
store type C // crash
```
> Fix unpickling type whose bounds depend on itself

- jvm/src/test/scala/tastyquery/TypeSuite.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
the problem was that `forceRoots` had some recursive forcing (not cyclic), and caused the roots map in Loader to be overwritten, solution is to update the roots map before forcing symbols.
The second commit then removes the unnecessary recursive forcing, but the test already passes in the first commit
fixes #105
> Fix package decls load

- jvm/src/test/scala/tastyquery/SignatureSuite.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
We can deal with them when they are direct AppliedTypes. There are other cases that dotc handles but that we do not handle yet, notably RefinedTypes.
> First step of dealing with Scala 2 existential types.

- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Names.scala
- shared/src/main/scala/tastyquery/ast/Signature.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- shared/src/test/scala/tastyquery/SignatureSuite.scala
- test-sources/src/main/scala/inheritance/MyArrayOps.scala
- test-sources/src/main/scala/inheritance/MyFlags.scala
it's not yet possible for scala 2 classes until we read the parents.
For this reason this PR is not enough to fix the issue https://github.com/scalacenter/tasty-query/issues/119, we should read parents for scala 2 classes
> erase ValueClasses defined in tasty

- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeMaps.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- shared/src/test/scala/tastyquery/SymbolSuite.scala
- shared/src/test/scala/tastyquery/TypeSuite.scala
Previously, `PackageClassSymbol` was a subclass of `ClassSymbol`. The notion of `DeclaringSymbol` was confused with `ClassSymbol`.
We now make these concepts entirely distinct:
* Rename `PackageClassSymbol` to `PackageSymbol`.
* Make `DeclaringSymbol` a `trait extends Symbol`.
* `PackageSymbol` extends `DeclaringSymbol` but not `ClassSymbol`.
* Move the logic for initialization to `DeclaringSymbol` and clearly name it as `ensureDeclsInitialized()`, since it is only ensuring that declarations are ready to be used; not that the symbol as a hole is ready.
* Remove `ClassSymbol.initialised`, since it is not used anymore.
> Make package symbols separate from ClassSymbol's.

- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/test/scala/tastyquery/TypeSuite.scala
We also standardize on `symbol` being the public accessor for the symbol of a `NamedType`, and use an private `computeSymbol()` as implementation detail.
> Remove Types.Symbolic. Deal with NamedType's and ThisType's separately.

- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/test/scala/tastyquery/TypeSuite.scala
Unlike in dotc, we don't have different periods, so we will always have the same parent list for any given class.
> Store the parents of a class in the ClassSymbol instead of the ClassInfo.

- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/test/scala/tastyquery/PositionSuite.scala
- shared/src/test/scala/tastyquery/ReadTreeSuite.scala
This way, we do not need to store a NoSymbol in the tree, and we do not have meaningless fields `rhs` and `symbol`.
> Use a dedicated tree node SelfDef for self type definitions.

- shared/src/main/scala/tastyquery/Contexts.scala
- shared/src/main/scala/tastyquery/Definitions.scala
- shared/src/main/scala/tastyquery/api/TastyQuery.scala
- shared/src/main/scala/tastyquery/ast/Symbols.scala
- shared/src/main/scala/tastyquery/ast/Trees.scala
- shared/src/main/scala/tastyquery/ast/TypeMaps.scala
- shared/src/main/scala/tastyquery/ast/TypeOps.scala
- shared/src/main/scala/tastyquery/ast/TypeTrees.scala
- shared/src/main/scala/tastyquery/ast/Types.scala
- shared/src/main/scala/tastyquery/reader/TreeUnpickler.scala
- shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- shared/src/main/scala/tastyquery/reader/classfiles/Classpaths.scala
- shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleFlagSet.scala
- shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- shared/src/test/scala/tastyquery/SignatureSuite.scala
- shared/src/test/scala/tastyquery/SymbolSuite.scala
- shared/src/test/scala/tastyquery/TypeSuite.scala
Previously, the hierarchy of `Symbol` was limited to `ClassSymbol`, `PackageSymbol` and `RegularSymbol`. `RegularSymbol`s could equally represent terms or (non-class) types.
In the latter case, their `declaredType` would contain a dubious encoding of the type definition. Notably, we used `WildcardTypeBounds` as a way to wrap `TypeBounds` in a `Type`, but that was a hack, and they had to be extracted everywhere.
Now, the hierarchy is more elaborate. In particular, we distinguish `TermSymbol`s, with a `declaredType: Type`, from the `TypeSymbol`s, which are either `ClassSymbol`s or `TypeSymbolWithBounds`, the latter being further classified and exposing `bounds: TypeBounds`.
Some aspects of `Type`s are refined to expose and manipulate the appropriate subtypes of `Symbol`s. In particular, …
> The Great Symbols Refactoring.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeTrees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
The designator is not a stable value. Only `name` and `symbol` should be accessed from the outside.
To hide the `designator`, we have to make `TermRef` and `TypeRef` non-case classes.
For testing purposes, we expose a `private[tastyquery]` access to the designator with a scary name.
These changes also allow to make `LookupIn` and `Scala2ExternalSymRef` `private[tastyquery]`, which furthers hide implementation details of the library.
> Lock down any access to the `designator` of `NamedType`s.

- tasty-query/shared/src/main/scala/tastyquery/Constants.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeTrees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
This way, the `TypeRef`s can be cached, and their resolved `symbol`s as well.
> Move the core type definitions to `Definitions`.

- build.sbt
Otherwise, the root project is set up for 2.12.x, and that confuses sbt-ci-release.
@julienrf Exactly the kinds of the things I could only discover with the snapshots ;)
> Set up scalaVersion and crossScalaVersions in ThisBuild.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- test-sources/src/main/scala/simple_trees/SpecialFunctionTypes.scala
Currently, only for N up to 22.
For higher arities, as well as for higher arities of `FunctionN`s, we will need to create declarations on-demand in the `scala` package, so this will need something more in the future.
> Fix #125: Create the scala.ContextFunctionN special classes.

- build.sbt
sbt-dynver is supposed to provide it.
> Remove the explicit setting of `version`.

- tasty-query/shared/src/main/scala/tastyquery/Contexts.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- test-sources/src/main/scala/synthetics/CaseClass.scala
in tasty, trees that point to the Root package are stored as `TERMREFpkg _root_`, so have a fully qualified name of `FullyQualifiedName(name"_root_" :: Nil)`. I adjust the method `findPackageFromRoot` to drop an initial `_root_`, so its optional to add it.
For context, the crash in #154 comes from reading the `_root_.scala.Product` parent of the case class, when determining if it is a value class in erasure
fixes #154
> resolve _root_ package ref

- tasty-query/shared/src/main/scala/tastyquery/Contexts.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
I think this one is more clean - i.e. by not adding new behaviour to `findPackageFromRoot`
> strip _root_ from FQN in nameTable

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
We introduce a generic method `Symbol.checkCompleted()`, which checks that all fields of a `Symbol` have been properly initialized.
We call that method at the end of reading a file, for all the symbols that were created while reading that file. This makes sure that by the time a `Symbol` gets in the hand of a user, it has been completely initialized.
> Check that all symbols are fully initialized

- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
All the code paths involving `ClassInfo` were dead code. Now that we have a significant portion of subtyping, I am confident that its need will not resurface later.
This introduces an `AssertionError` path in `TypeRef.underlying`, which is not nice, but it also removes some `???` code paths in other places.
It would be worth investigating whether we could make `TypeRef` not a `TypeProxy`, but a cursory attempt met other issues.
> Remove `ClassInfo`.

- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- test-sources/src/main/scala/javadefined/BagOfGenJavaDefinitions.java
I ran a test case that forced all root symbols in the `jre/lib` jars - this exposed that multiple throws clauses are not supported, and also some classes shipped in rt.jar are compiled by java 1.1 (i.e. have classfile version 45.3)
> support java 45.3, multiple throws on method

- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ClasspathEntrySuite.scala
- tasty-query/shared/src/test/scala/tastyquery/Paths.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/OverloadedApply.scala
With some cleanups before we get there.
> Fix #187: getDecl considers no-signature as an identifying feature.

- tasty-query/shared/src/main/scala/tastyquery/Exceptions.scala
- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
This allows to more safely manipulate `NoPrefix`, as we can be sure that it is never used where a proper `Type` is needed.
> Make `NoPrefix` and `Type` direct, exclusive subcases of `Prefix`.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeTrees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
Highlighted outcomes:
* `EmptyTree`, `EmptyTypeTree` and `EmptyTypeIdent` are gone.
* `Tree` and `TypeTree` are `sealed`.
* All `case class`es are `final`; no more `abstract case class`es.
> Refactor Trees and TypeTrees.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/subtyping/paths/NestedClasses.scala
It turns out that all the places where we used `accessibleThisType` were supposed to use the (internal) `thisType` instead. We replace them all, and remove the now-dead-code `accessibleThisType`.
> Fix #193: Replace all uses of accessibleThisType by thisType.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TestUtils.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/inheritance/PrivateOverrides.scala
- test-sources/src/main/scala/inheritance/SameTasty.scala
When looking directly at a class, we should find its `Private` members, but not ones inherited from superclasses.
Even for the class itself, we should never find `ParamAccessor`s. If a `ParamAccessor` is actually meant, it will be a symbol-based `TermRef`, not a name-based one.
> Fix #195: Handle Private and ParamAccessor in `findMember`.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeTrees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
`TermTree`s are the only ones that have a generic `tpe`. Most term trees accept only `TermTree`s as arguments. For example, the `fun` and `args` or an `Apply` tree are all `TermTree`s.
Restricting `tpe` to `TermTree`s allows to get rid of many uses of `NoType`.
The pattern of `CaseDef` is limited to `PatternTree`s. Some "physical" TASTy tags are shared between similarly-looking term trees and pattern trees. The unpickler tells them apart. This way, when looking at patterns, the semantics are clearer.
> Add tree categories for term trees and pattern trees.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
Subclasses of `Symbol` admit only specific kinds of defining `Tree`s.
> Give more precise types to the result of Symbol.tree.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
The `Template.parents` are all `Tree`s, now that `TypeTree`s are `Tree`s.
> Remove a useless `collect`.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/Function.scala
- test-sources/src/main/scala/simple_trees/RefinedType.scala
Including their members which can contain RECthis, METHODtype, and POLYtype.
Fix #6, fix #16, fix #20, fix #21.
This is not enough for #213 yet, since they are not handled correctly in member selection nor subtyping yet.
> Support reading all sorts of refinement types.

- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/Annotations.scala
This is the bare minimum to read the annotations.
There will be followups for
* Convenience accessors for annotation info (class symbol, constant arguments, etc.)
* Correct treatment of `targetName`
> Read annotations from TASTy.

- tasty-query/js/src/main/scala/tastyquery/nodejs/ClasspathLoaders.scala
- tasty-query/jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- tasty-query/shared/src/main/scala/tastyquery/Classpaths.scala
This is fine, since they are immutable data-only containers. It allows to create these in a more hierarchical way in the loaders.
We deprecate the `Classpath.from` method, as it does not add any value anymore.
> Make the `Classpath` and `Classpath.Entry` constructors public.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/Variances.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
This solves the issue of tasty-mima mentioned at
https://github.com/scalacenter/tasty-mima/blob/e88400d0981c079df60abacb3663ac8ac08c11db/test-lib-v1/src/main/scala/testlib/membertypechanges/MemberTypeChanges.scala#L3-L6
> Handle polymorphic type aliases in subtyping.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
This is necessary to construct `RecType`s from scratch outside of tasty-query.
`LambdaType.paramRefs`, which performs a similar role, is already a public val.
> Make `RecType.recThis` a public val.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
* They should be defined as `TypeLambda`s, not `PolyType`s.
* When there is a non-class tycon in an AppliedType on the left of a subtyping comparison, we need to try the `superType`, to handle the case where it is a `TypeRef` to a polymorphic type alias.
> Correctly handle the `scala.|` and `scala.&` aliases in subtyping.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
They represent by-name params to function types.
> Handle `ExprType`s in subtyping.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
It was incorrectly initialized as a `TypeAlias` instead of an `OpaqueTypeAlias`.
> Correctly fill in typeDef for opaque type aliases without bounds.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/inheritance/Overrides.scala
It is a public, safer variant of `matchingDecl`. Unlike `overriddenSymbol` and `overridingSymbol`, it can find matching symbols in unrelated classes, but it requires a common subclass as argument.
Alternative to #235 that lets the user of the library implement `runtimeImplementingSymbol` and `nextSuperSymbol` in user-space.
/cc @shardulc
> Add a method `TermOrTypeSymbol.matchingSymbol`.

- README.md
The deleted sections have been moved to the readme of TASTy-MiMa itself.
> Clean up TASTy-MiMa-related stuff from the readme.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
In TASTy, their info is stored as a TypeLambda over "opaque TypeBounds" (BoundedType's in our implementation). However, that does not fit our model for `TypeMemberDefinition`.
We now distribute `TypeLambda`s over `BoundedType`s so that we can correctly handle polymorphic opaque type aliases.
We do not handle variance yet.
This commit includes a fix to `dealias` not to follow opaque type aliases. From a public point of view, it does not make sense to do so.
> Handle polymorphic opaque type aliases.

- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
They were already handled on the lhs, but not on the rhs.
Refining annotations are supposed to prevent this, but currently we treat them as the non-refining ones.
> Handle (non-refining) `AnnotatedType`s in subtyping.

- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/crosspackagetasty/TopLevelOpaqueTypeAlias.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
Unfortunately, #179 also happens for Scala 3 package objects created for top-level definitions. So in fact we have to load all possible package objects in the fallback of `PackageRef.findMember`.
> Look in *all* package objects for the PackageRef.findMember fallback.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/inheritance/CtorParamsNormalization.scala
I was not able to reproduce the issue in a standalone test, but apparently it is possible to have *both* a `New` with an `AppliedType` (hence, monomorphic) wrapped in a `TypeApply`. This would attempt to reapply type parameters to an already monomorphic type, which crashed.
We are now a bit more tolerant, and apply type parameter lists to the type of the `New` as long as we have a polymorphic type. We stop applying further type parameter lists when the type is fully monomorphic.
---
The first commit contains more tests that were an attempt at reproducing the above issue. They don't, but the tests are valuable anyway.
> Be even more tolerant when typing polymorphic `Apply(New, ...)`.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/simple_trees/HigherKinded.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
* When converting them from TASTy, and
* In subtyping.
> Handle higher-kinded type param refs.

- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/EvilClassNames.scala
The previous computation was not able to deal with top-level classes containing `$` signs. Now, we only consider a class to be nested (or companion) if some other class in the same directory is a *prefix* of it.
When only `.tasty` files are present, all classes are top-level.
> Better computation of top-level v nested classfiles in Loaders.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/ForExpressions.scala
And with that, we solve the last issue caused by tasty-query in the langoustine project.
There will remain one issue to fix on tasty-mima's side.
> Handle SHAREDterm's in `readPattern`.

- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- test-sources/src/main/scala/simple_trees/UnionType.scala
In general, of array of `AppliedType(tycon, args)` where `tycon` is a type alias to a `TypeLambda`.
> Fix erasure of array of union types.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
Reserve `ExprType` for by-name params only.
This is closer to the contents of TASTy and of pickles, and is also closer to a user understanding of the language.
We then rename `ExprType` to `ByNameType`.
> Do not wrap the result type of paramless methods in ExprType.

- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
We create a new category of trees, `TypeDefinitionTree`, for the rhs of type definitions: type members, type parameters and type captures. They isolate the weird, context-dependent meaning of TYPEBOUNDS, TYPEBOUNDStpt (sometimes wrapped in LAMBDAtpt) from the hierarchy of `Type`s and the corresponding `TypeTree`s.
The `TypeDefinitionTree`s are read from TASTy using a few isolated functions, and they are transformed depending on their context into `TypeBounds`, `WildcardTypeBounds`, `TypeMemberDefinition`s, etc.
These changes allow to completely remove `BoundedType` and `NamedTypeBounds` from the hierarchy of `Type`s, so that we are certain they do not leak to the semantic areas of the API.
> Consolidate Trees for type bounds and type definitions.

- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
We make `signature` and `targetName` public. All terms now have a `signature` (it is non-optional). For fields, it is the signature of the JVM/IR getter method, which is also the descriptor of the underlying JVM field.
In contrast, `signedName` does not return a `SignedName` for parameterless methods anymore. It returns a `SignedName` if and only if a `SignedName` is required to find the symbol through `getDecl`. To access the JVM signature of a parameterless method, `signature` can be used.
---
~~Based on #257.~~
> Make signature, targetName and signedName more user-friendly.

- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
It alleges that the test is not correct, but it was actually made correct in dea21ab080170f205050b02ca92d83ff2362546d.
> Remove a stray TODO comment in SignatureSuite.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/subtyping/paths/Paths.scala
This allows subtyping of refinements to work out for poly-kinded type refinements implemented by polymorphic classes.
Follow-up to https://github.com/scalacenter/tasty-query/pull/268#pullrequestreview-1356309953
> Subtyping: eta-expand tp1 when tp2 is a TypeLambda.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
That allows userland code to *query* a Type for a member by its name, without having to a priori construct a NamedType and catch `MemberNotFoundException`.
> Add a method Type.lookupMember(name: Name): Option[NamedTyped].

- build.sbt
- test-sources/src/main/scala/symbolic_--/lazyCons.scala
That is officially deprecated in Scala 3 now, and we had no test left mentioning it.
We can now enable `-Xfatal-warnings` for Scala in `test-sources`.
> Remove the `symbolic_--` package from the test-sources.

- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
For `RecType`/`RecThis`, use the infrastructure for enclosing binders in the `localCtx`, like we do for `LambdaType`s.
For the `THIS` references to the enclosing refinement class, we now create the magic refinement class symbols along with all the other symbols, and then we specially treat `REFINEDtpt` in `readType` position to fetch that symbol.
> Clean up the way we read recursive types.

- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
In particular, for `RecType`s.
This makes the scala-debug-adapter CI pass again.
> Implement erasure for the remaining TypeProxy's.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- Its type param must be covariant.
- The TypeRef to the type param must have a `ThisType` prefix in the parent constructors.
> Fix the definition of `RepeatedParamClass`.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMatching.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
They make sense at the spec level, and are needed by the tasty checker.
> Make ClassSymbol.thisType and Type.typeParams public.

- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/DefaultParams.scala
- test-sources/src/main/scala/simple_trees/ValueClass.scala
@nicolasstucki Do you want to review this one? There's not everything yet, notably the `InternalError`s, but it's already something.
> Fixes for applying tasty-mima across Scala 2 and Scala 3

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/subtyping/TypesFromTASTy.scala
When we compute the bounds an opaque type alias as seen from a this prefix of its enclosing class, we are allowed to see the alias.
> Implement selective transparency of opaque type aliases.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
Reverts scalacenter/tasty-query#309
> Revert "Skip the problematic getClass() definitions in Scala 2 prim classes."

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Scala2Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMatching.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
A `Type` is now what the spec calls a type. It does not include `WildcardTypeBounds`, `MethodicType` nor `PackageRef` anymore. For that, the super traits `TypeOrMethodic`, `TypeOrWildcard`, or `NonEmptyPrefix` must be used instead.
`TypeOrWildcard`s can only be used as type arguments of `AppliedType`s. `TypeOrMethodic`s are used as the underlying type of term members.
Arbitrary terms have `TermType`s. These are real `Type`s, `MethodicType`s or `PackageRef`s.
> The Great Types Refactoring: Adapt our Types hierarchy to the spec.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMatching.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
So that selecting from a `val` term refinement indeed gives a stable `TermRef`.
This also brings term member resolution closer to the spec.
> Include the isStable flag in `TermMemberResult`.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
`T.baseType(C)` now always returns a type of the following shape:
* `p.C` if `C` is monomorphic, or
* `p.C[...Ts]` if `C` is polymorphic.
> Make `baseType` follow the spec in terms of what shape it returns.

- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Scala2Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
They are always available syntactically. They were the only thing for which `Printers` needed some private access.
> Give access to the typeDef and bounds of type symbols without Context.

- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Scala2Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMatching.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
Concretely, rename isSubclass, isSubtype and isSubprefix to isSubClass, isSubType and isSubPrefix. It makes it more consistent with isSubTypeOrMethodic and isSameType.
> Harmonize isSubX methods to start X with an uppercase.

- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
As a by-product, this PR closes #273. APIs that are safe to use without a full classpath do not take a `using Context` as parameter.
> Remove useless contexts

- tasty-query/shared/src/main/scala/tastyquery/Flags.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
And hide the actual fields, whose name ends in ' '.
> Make Scala 2 getters appear as fields, to be consistent with Scala 3.

- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/OverloadedApply.scala
Although `Nothing` erases to the runtime class `scala.runtime.Nothing$`, it appears as `scala.Nothing` in signatures.
> Fix #334: Make the signatureName of Nothing be `scala.Nothing`.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/Descriptors.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/PositionUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
It statically makes sure that we never access anything that requires reading another file.
This change surfaced a couple places where there could potentially be external reading, and which are now a bit more complicated to fit the static restriction. The most prominent example is `TreeUnpickler.readWithin`, which also suggested that we decouple reading the `privateWithin` from the flags (to only do it after `createSymbols()` is over).
> Introduce a more restrictive `ReaderContext` inside `reader.*`.

- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
Previously, we had to compute the source files to load in an ad hoc way, based on the name of the class we were looking for. Now that positions carry their source file, we can directly use that information to load the appropriate source code.
> Use pos.sourceFile to load source code in PositionSuite.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Signatures.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/UnionType.scala
- test-sources/src/main/scala/simple_trees/UnionTypeJoin.scala
- test-sources/src/main/scala/simple_trees/UnitErasure.scala
After these changes, the `.symbol` of *every* `TermReferenceTree` (`Ident` or `Select`) in the `dotty` package (and subpackages) resolves without exception.
> Fix #336: Fix all the member-not-founds in the dotty codebase.

- .github/workflows/release.yml
- .github/workflows/scala.yml
- project/build.properties
Temurin is the successor of AdoptJDK.
Closes #353.
> Add JDK 21 to the CI and use the Temurin distribution.

- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- test-sources/src/main/scala/simple_trees/GenericClassWithTypeParamDependencies.scala
- test-sources/src/main/scala/simple_trees/GenericMethodWithTypeParamDependencies.scala
- test-sources/src/main/scala/simple_trees/SpecialFunctionTypes.scala
- test-sources/src/main/scala/simple_trees/Tuples.scala
> Handle bounds of TypeParamRef's in subtyping, and other tests.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SymbolSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
These include all kinds of names except `SignedName`. Having dedicated traits for these allows to make our API and implementation more type-safe.
> Introduce `UnsignedName` and `UnsignedTermName`.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SubtypingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
This removes the last magic class (i.e., class that is not spec-related) from `Definitions`.
> Replace the magic `<repeated>` class by a dedicated `RepeatedType`.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/PositionUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyFormat.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyHeaderUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
We already had a source dependency on tasty-core because of the Scala.js artifact. This means that things from the tasty-core artifact leaked in our public API.
Depending on the upstream tasty-core, while somewhat convenient, also constrained us to only be able to read TASTy from a published version of dotc.
We now source-in what we need from tasty-core (which is not that much) as package-private.
> Source-in what we need from tasty-core.

- tasty-query/js/src/main/scala/tastyquery/nodejs/ClasspathLoaders.scala
- tasty-query/jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- tasty-query/shared/src/main/scala/tastyquery/Classpaths.scala
- tasty-query/shared/src/main/scala/tastyquery/Contexts.scala
- tasty-query/shared/src/main/scala/tastyquery/Exceptions.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ClasspathEntrySuite.scala
- tasty-query/shared/src/test/scala/tastyquery/RestrictedUnpicklingSuite.scala
The implementation in `jdk.ClasspathLoaders` and
`nodejs.ClasspathLoaders` still actually reads everything eagerly. However, a third-party implementation that wants to read things differently could now do so.
> Redesign Classpaths so that they could lazily read their files.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Substituters.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/Annotations.scala
It gives access to the symbols of the declared type and term parameters of a method. This is useful for information that is not available in the `MethodicType`s, such as modifiers and annotations.
> Introduce TermSymbol.paramSymss.

- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleFormat.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
We do not read all kinds of trees. Only the ones that do not contain definitions nor pattern matches (which means no `try`s either). If we encounter a kind of tree we do not support, we bail and replace the annotation argument with a placeholder.
We have to cheat for the selection of the constructor because the pickles do not contain a signed name reference. However, we have enough information for the most important methods of `Annotation` to actually work.
> Implement reading annotations from Scala 2 pickles.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
The information stored in `myParentsInit` can be found in the `tree` of the symbol, so we directly get it from there. This avoids storing a lambda with delayed evaluation in the symbols, which is more in line with our model of only storing *data*, not *computations*.
Note that we cannot do this for the other information we store in symbols, because they can come from Scala 2 pickles and Java class files, which have no trees. `myParentsInit` is the odd one in that it is already a TASTy-specific alternative to `myParents`. `myParents` is directly filled in for Scala 2 and Java.
> Remove `myParentsInit`/`withParentsDelayed`; use the `tree` instead.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Flags.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
`VarianceFlags` was dead code.
`TypeParameter` and `ClassTypeParam` are redundant with the actual classes of type symbols.
> Remove useless flags.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Constants.scala
**Potentially controversial.**
This is technically a compatibility breach, both at the binary and TASTy level. However, I don't see how anyone could have meaningfully extended `Constant` (also we have 2 users so far).
> Make Constants.Constant final.

- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- test-sources/src/main/scala/simple_trees/Constants.scala
I only wrote tests for the weirdest forms of trees.
> Add a basic printer for trees, with a method Tree.showBasic.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Constants.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/Constants.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/JavaSignatures.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/javadefined/BagOfJavaDefinitions.java
- test-sources/src/main/scala/javadefined/JavaAnnotAnnotValue.java
- test-sources/src/main/scala/javadefined/JavaAnnotArrayValue.java
- test-sources/src/main/scala/javadefined/JavaAnnotClassRetention.java
- test-sources/src/main/scala/javadefined/JavaAnnotClassValue.java
- test-sources/src/main/scala/javadefined/JavaAnnotEnumValue.java
- test-sources/src/main/scala/javadefined/JavaAnnotMultiValues.java
- test-sources/src/main/scala/javadefined/JavaAnnotSingleValue.java
- test-sources/src/main/scala/javadefined/JavaAnnotations.java
Bonus: read Java parameter names.
> Read Java annotations.

- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- test-sources/src/main/scala/simple_trees/ObjectWithSelf.scala
Re-create the correct self type which is a term reference to the accompanying lazy val.
> Work around lampepfl/dotty#19019: patch the SelfDef of inner module classes.

- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
We had a long-standing issue with "orphan" `TYPEsym`s and `VALsym`s in Scala 2 pickles. We were replacing them by "no symbol" themselves, because we did not know what to do with them.
Issue #397 finally provided a good setup to diagnose it. It turns out that those orphan symbols can be found as term and type params of method types and poly types, in particular, Scala 2's encoding of type lambdas, which can be produced by kind-projector.
Since we now have a good reason to have those orphan symbols, we bite the bullet and allocate one global symbol to "host" all those symbols coming from Scala 2.
---
Locally tested with `libraryDependencies += "org.scalaz" % "scalaz-core_2.13" % "7.3.5",` on the testSources classpath.
> Fix #397: Use a fake owner for orphan symbols in Scala 2 pickles.

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
If we have a `package object` that extends other classes, we may have to look member selections among inherited members. This is done by `getMember` instead of `getDecl`.
To test this, we need a Scala 2 `package object` with an `extends` clause. There is no such thing in the standard library, which is our only source of Scala 2 code, unfortunately. So we don't add a test for that.
---
Locally, given the following dependency in the `testSources`:
```scala
libraryDependencies += "com.softwaremill.sttp.client" % "core_2.13" % "2.0.4",
```
the following `TypeSuite` test used to fail before, and now works:
```scala
testWithContext("test") {
import Signatures.*
val sttpClientPackage = ctx.findPackage("sttp.client")
val UriContextName = termName("UriContext")
val UriInterpolatorClass = …
```
> Fix #398: Include inherited members in the PackageRef fallback lookup.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/RecursiveMatchType.scala
This mostly acts as a fast path. However, for the particular case of static recursive match types, it more critically cuts some infinite recursion.
Normally, when a match type refers to itself, it would do so through a `ThisType`. Computing `asSeenFrom` for a `ThisType` prefix already cuts the infinite recursion because it is, by construction, a no-op.
However, for static recursive match types, the compiler makes them refer to themselves through their public, static prefix. This caused the infinite recursion observed in https://github.com/scalacenter/tasty-query/issues/401.
To avoid the issue, we use another shortcut to `asSeenFrom`: if the type we map over does not contain any `ThisType`, we also know it will be a no-op. We store that as a lazy val `isPrefixDependent` of `TermSymbol` and …
> Fix #401: Avoid asSeenFrom for types/bounds that don't depend on the prefix.

- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
At the loader level:
Only remove package data entries *after* successful loading.
At the package symbol level:
While loading new symbols from the loader, all new declarations are put in a `pendingDeclarations` safe zone. They are committed to `myDeclarations` only after the whole operation successfully complets.
This way, if a failure happens while reading one root, it does not corrupt the other roots in the same package.
---
Locally tested with
```scala
libraryDependencies += "dev.zio" %% "zio-test" % "2.0.16",
```
and the following `TypeSuite` test:
```scala
testWithContext("issue-412") {
val zioPackage = ctx.findPackage("zio")
// Cause the initial failure
intercept[TastyFormatException](zioPackage.declarations)
val decl1 = zioPackage.findDecl(typeName("ZInputStream")) // before …
```
> Fix #412: Protect the state of packages and loaders from exceptions.

- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
This mimics how we ready .tasty files. First, we create all the symbols defined in the pickle, without reading their types. Only then do we read all the types of all the symbols.
This avoids tricky recursive situations, notably in the presence of complicated existentials and refinement classes mixed together.
Some of the hacks we had to do for refinement classes disappear as a result, because they are not needed anymore.
We can also treat `MODULEsym`'s like other term symbols, without separate code paths.
> Scala 2 pickle reader: first read all symbols, then all their types.

- build.sbt
- scala2-test-sources/src/main/scala/scalatwo/Macros.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Names.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
It contains an annotation with a subtree that is an `IDENTtree` without prefix nor symbol, with the name `macro`. That is then `Apply`ed and `TypeApply`ed in ways that make no semantic sense.
We define a special symbol in `Definitions`, which we attach to such fake identifiers.
> Do not crash when reading a Scala 2 `macro` definition.

- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
It does not seem that the upstream issue will be fixed any time soon due to binary compatibility concerns. Nevertheless, it makes no sense, and it is not possible possible to create a *value* of a "package type".
Therefore, we work around the issue by tolerating a `PackageRef` as the type of a PARAM of an inline accessor method. We replace it by `Nothing`, which matches the fact that no value can be created for it.
Note that the *signature* and therefore the *signed name* of such a method will be different from what dotc computes, so it will still be semantically broken.
> Work around https://github.com/lampepfl/dotty/issues/19237

- tasty-query/shared/src/main/scala/tastyquery/Types.scala
There was an infinite recursion between looking up a type member of a refinement and subtyping of that member against the same refinement. This came from computing the merged TypeBounds of the type member during subtyping, which used subtyping to get rid of useless bounds.
We break the cycle by not using subtyping when merging the TypeBounds of a type member anymore. Instead, we manually dive into possibly-higher-kinded bounds (`TypeLambda`s themselves, but also `Nothing` and `AnyKind`), and otherwise construction a union or intersection type.
Unwrapping higher-kinded bounds is necessary because constructing a uniont or intersection requires proper types.
---
I did not manage to come up with an isolated reproduction, unfortunately. But with the dependency in #423, I can now successfully …
> Fix #423: Merge the TypeBounds of type members without needing subtyping.

- build.sbt
Set `versionPolicyIntention` to `BinaryAndSourceCompatible` for the upcoming v1.2.1.
Remove previous MiMa filters.
> Post release v1.2.0.

- build.sbt
- tasty-query/js/src/main/scala/tastyquery/nodejs/ClasspathLoaders.scala
- tasty-query/jvm/src/main/scala/tastyquery/jdk/ClasspathLoaders.scala
- tasty-query/shared/src/main/scala/tastyquery/Annotations.scala
- tasty-query/shared/src/main/scala/tastyquery/Classpaths.scala
- tasty-query/shared/src/main/scala/tastyquery/Contexts.scala
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Symbols.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/Utils.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/Loaders.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/ReaderContext.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/ClasspathEntrySuite.scala
- tasty-query/shared/src/test/scala/tastyquery/RestrictedUnpicklingSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/UnrestrictedUnpicklingSuite.scala
On the condition that the `ClasspathEntry`s used to create the `Context` are thread-safe.
> Make the entire API thread-safe.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyFormat.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/TestUtils.scala
- tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala
- test-sources/src/main/scala/simple_trees/AccessModifiers.scala
- test-sources/src/main/scala/simple_trees/AnyMethods.scala
- test-sources/src/main/scala/simple_trees/Match.scala
- test-sources/src/main/scala/simple_trees/RecursiveMatchType.scala
- test-sources/src/main/scala/simple_trees/RefinedTypeTree.scala
- test-sources/src/main/scala/simple_trees/TypeRefIn.scala
- test-sources/src/main/scala/simple_trees/Uninitialized.scala
- test-sources/src/main/scala/simple_trees/ValueClass.scala
- test-sources/src/main/scala/simple_trees/WildcardTypeApplication.scala
Changes notably include:
* Handling `Lambda`s that are poly functions.
* Weakening a test affected by #436.
> Upgrade to Scala 3.4.0 and support its TASTy format.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/Definitions.scala
- tasty-query/shared/src/main/scala/tastyquery/Erasure.scala
- tasty-query/shared/src/main/scala/tastyquery/Printers.scala
- tasty-query/shared/src/main/scala/tastyquery/Subtyping.scala
- tasty-query/shared/src/main/scala/tastyquery/Traversers.scala
- tasty-query/shared/src/main/scala/tastyquery/Trees.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeMaps.scala
- tasty-query/shared/src/main/scala/tastyquery/TypeOps.scala
- tasty-query/shared/src/main/scala/tastyquery/Types.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyFormat.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PositionSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/WholeClasspathSuite.scala
- test-sources/src/main/scala/simple_trees/AccessModifiers.scala
- test-sources/src/main/scala/simple_trees/QuotesAndSplices.scala
Changes notably include:
* Support `Quote` and `QuotePattern` nodes.
* Support `FlexibleType`s.
> Upgrade to Scala 3.5.0 and support its TASTy format.

- build.sbt
Set `versionPolicyIntention` to `BinaryAndSourceCompatible` for the upcoming v1.4.1.
Re-enable TASTy-MiMa by forcing a newer version of the underlying tasty-query.
> Post release v1.4.0.

- build.sbt
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyFormat.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
- tasty-query/shared/src/test/scala/tastyquery/ReadTreeSuite.scala
- tasty-query/shared/src/test/scala/tastyquery/SignatureSuite.scala
With changes to the inferred bound of match types.
> Upgrade to Scala 3.6.3.

- build.sbt
Set `versionPolicyIntention` to `BinaryAndSourceCompatible` for the upcoming v1.5.1.
Re-enable TASTy-MiMa by forcing a newer version of the underlying tasty-query.
> Post release v1.5.0.

- build.sbt
- project/plugins.sbt
- tasty-query/shared/src/main/scala/tastyquery/reader/classfiles/ClassfileParser.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/PickleReader.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/pickles/Unpickler.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TastyFormat.scala
- tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala
- tasty-query/shared/src/test/scala/tastyquery/PrintersTest.scala
Upgrades to Scala 3.7.0 and 2.13.16 for Scala 2 tests. Also upgrades Scala.js to 1.19.0 to match the compiler upgrade in https://github.com/scala/scala3/pull/23026.
> Upgrade to Scala 3.7.1.

- project/build.properties
- project/plugins.sbt
This is necessary to publish to the new Maven Central Portal.
> Upgrade to sbt 1.11.3 and sbt-ci-release 1.11.0.
